# sudo docker compose up -d
version: '3.8'

services:

  db:
    container_name: postgres_drf
    image: postgres:latest
    # restart: always
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"

  web:
    build:
      context: ../upload_files_drf
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    env_file:
      - ./.env
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:1.21.3-alpine
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web

  redis-m1:
    image: redis
    restart: always

  worker:
    build:
      context: ../upload_files_drf
    restart: always
    depends_on:
      - redis-m1
      - web
      - db
    env_file:
      - ./.env
    command: >
      sh -c "celery -A upload_files_drf worker --loglevel=INFO"

volumes:
  db_value:
  static_value:
  media_value:
